routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ApplicantController;
use App\Http\Controllers\ApplicationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard',                            [HomeController::class, 'index'])->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('/applications',                    ApplicationController::class)->middleware('auth');
Route::resource('/applicants',                      ApplicantController::class)->except('index')->middleware('auth');
Route::resource('/projects',                        ProjectController::class)->middleware('auth');
Route::resource('/profiles',                         ProfileController::class)->middleware('auth');

Route::get('projects/{project}/applicants/',        [ApplicantController::class, 'index'])->name('applicants.index')->middleware('auth');
Route::get('projects/{project}/applicants/{user}',  [ApplicantController::class, 'acceptApplicant'])->name('applicants.accept');
Route::get('projects/{project}/assembleTeam',       [ApplicantController::class, 'assembleTeam'])->name('applicants.assemble');
Route::get('/ajax/projects', [ProjectController::class, 'getProjects'])->name('ajax.projects');
require __DIR__.'/auth.php';

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Skill;
use App\Models\Academy;
use App\Models\Project;
use Illuminate\Http\Request;
use App\Models\ProjectRequirement;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\ProfilesRequest;


class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profiles = Project::with('user', 'user.skills')
            ->where('user_id', auth()->user()->id)
            ->latest()
            ->get();

        return view('pages.profiles.index', compact('profiles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('pages.profiles.show', ['user' => User::where('id', $id)->first(), 'skills' => Skill::all(),'project' => Project::where('id', $id)->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('pages.profiles.edit', ['user' => User::where('id', $id)->first(), 'skills' => Skill::all(), 'academies' => Academy::all(), 'requirements' => ProjectRequirement::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProfilesRequest $request, $id)
    {
        $userAvatar = User::where('id', Auth::id())->first();
        $id = Auth::id();


        if($request->hasFile('img') || $userAvatar->avatar == null){

            $request->validate([

                'img' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',

            ]);

            if($userAvatar->avatar != null) {

                unlink(public_path("assets/profile/". $userAvatar->avatar));

            }

            $file = $request->file('img');

            $extension = $file->getClientOriginalExtension(); // getting image extension

            $filename =time().'.'.$extension;

            $file->move('assets/profile/', $filename);

            User::where('id', $id)->update([

                'avatar' => $filename,
            ]);

        }

        User::where('id', $id)->update([

            'name' => $request->input('name'),
            'surname' => $request->input('surname'),
            'email' => $request->input('email'),
            'biography' => $request->input('biography'),
            ]);

        // List all arrays input
        $input['skills'] = $request->input('skills');
        // $input['academies'] = $request->input('academies');

        $userAvatar->skills()->sync($input['skills']);
        $userAvatar->academy_id = intval($request->input('academies'));

        $userAvatar->save();

        if($userAvatar->name != null && $userAvatar->surname != null && $userAvatar->email != null && $userAvatar->biography != null && $userAvatar->avatar != null && $userAvatar->skills() !=null && $userAvatar->academy_id !=null){
            User::where('id', $id)->update([

                'profile_complete' => 1
            ]);
        }


        return redirect()->route('profiles.edit', ['profile' => auth()->id()])->with('status', 'Project Created');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/profiles/edit.blade.php
<x-app-layout>
    <form action="{{ route('profiles.update', ['profile' => $user->id]) }}" method="POST" autocomplete="off" enctype="multipart/form-data">
        @csrf
        @method('put')

<div class="myprofile">
    <div class="profile-left prof-row">
        <div class="prof-title">
            <h1 class="h3">My Profile</h1>
        </div>

        <div class="profile-details d-flex mt-3">
            <div class="detail-left half mt-5">
                <div class="pic mt-5">
                @if ($user->avatar)
                    <img class="img-thumbnail" name="avatar" width="90px" src="{{ url('assets/profile/'.$user->avatar) }}" alt="User image">
                @else
                    <img class="img-thumbnail" width="90px"
                        src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="User image">
                @endif

                    <input type="file" name="img" id="inp-pic" hidden>
                    <label for="inp-pic" style="cursor : pointer;" class="mt-4">Click here to upload an image</label>
                </div>

            </div>

            <div class="detail-right half">
                <div class="prof-name margin-prof">
                <div class="mt-4 mb-0 input left form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                    <input type="text" name="name"  class="block mt-1 w-full text-line form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" required="true" value="{{ $user->name }}"   placeholder="Name">
                    @if ($errors->has('name'))
                      <span class="error text-danger"
                            id="name-error"
                            for="input-name">{{ $errors->first('name') }}</span>

                    @endif
                </div>
                </div>

                <div class="prof-name">
                    <div class="mt-1 mb-0 input left form-group{{ $errors->has('surname') ? ' has-danger' : '' }}">
                        <input type="text" name="surname"  class="block mt-1 w-full text-line form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" required="true" value="{{ $user->surname }}"   placeholder="Surname">
                        @if ($errors->has('surname'))
                          <span class="error text-danger"
                                id="surname-error"
                                for="input-surname">{{ $errors->first('surname') }}</span>

                        @endif
                    </div>
                    </div>
                    <div class="prof-name">
                        <div class="mt-1 mb-0 input left form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                            <input type="text" name="email"  class="block mt-1 w-full text-line form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" required="true" value="{{ $user->email }}"   placeholder="Email">
                            @if ($errors->has('email'))
                              <span class="error text-danger"
                                    id="email-error"
                                    for="input-email">{{ $errors->first('email') }}</span>

                            @endif
                        </div>
                        </div>
            </div>
        </div>

        {{-- Biography edit --}}
        <div class="prof-detail mt-5">
        <div class="mt-4 mb-4 ml-0 flex-column form-group{{ $errors->has('biography') ? ' has-danger' : '' }}">
        <strong class="createdesc">Biography</strong><br>
        <textarea class="form-control {{ $errors->has('biography') ? ' is-invalid' : '' }} createtextarea"  name="biography" placeholder="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.">{{ $user->biography }}</textarea>

        @if ($errors->has('biography'))
        <span class="error text-danger"
        id="biography-error"
        value="{{ $user->biography }}"
        for="input-biography">{{ $errors->first('biography') }}</span>

        @endif

        </div>
    </div>

    </div>

    <div class="profile-right prof-row">
        <div class="prof-title">
            <h1 class="h3">Skills</h1>
            <div class="prof-skills">
                <div class="input-group-text skillscheck">
                    @foreach ($skills as $item)

                        @php($is = true)

                          @foreach ($user->skills as $skill)

                          @if ($skill->pivot->skill_id == $item->id)

                            <input type="checkbox" name="skills[]" value="{{ $item->id }}" id="{{ $item->id }}" aria-label="Checkbox for following text input" checked class="d-none">

                            <label class="btn-selected2 skill" style="cursor: pointer;" for="{{ $item->id }}">{{ $item->name }}</label>

                              @php($is = false)
                              @break
                          @endif
                          @endforeach



                        @if($is)
                        <input type="checkbox" name="skills[]" value="{{ $item->id }}" id="{{ $item->id }}" aria-label="Checkbox for following text input" class="d-none">
                        <label class="btn-default2 skill" style="cursor: pointer;" for="{{ $item->id }}">{{ $item->name }}</label>
                        @endif

                    @endforeach


                        </div>
                        @if ($errors->has('skills'))
                        <span class="error text-danger mt-3"
                              id="skills-error"
                              for="input-skills">{{ $errors->first('skills') }}</span>

                      @endif
            </div>
        </div>

        <div class="academies mb-5">
            <div class="prof-title mb-0 mt-0">
                <h1 class="h3 mb-0 mt-3">Academies</h1></div>
            <div class="input-group-text academieprofscheck">
                @foreach ($academies as $itemm)

                    @php($is = true)
                    {{-- {{ dd($user->academy)}} --}}
                      @foreach ($user->academy as $academy)
                      {{-- {{ dd($academy->pivot->academy_id)}} --}}
                      @if ($user->academy_id == $itemm->id)

                        <input type="checkbox" name="academies[]" value="{{ $itemm->id }}" id="{{ $itemm->id }}" aria-label="Checkbox for following text input" checked class="d-none">

                        <label class="btn-selected prof-academy-select" style="cursor: pointer;" for="{{ $itemm->id }}">{{ $itemm->name }}</label>

                          @php($is = false)
                          @break
                      @endif
                      @endforeach



                    @if($is)
                    <input type="checkbox" name="academies[]" value="{{ $itemm->id }}" id="{{ $itemm->id }}" aria-label="Checkbox for following text input" class="d-none">
                    <label class="btn-default prof-academy-select" style="cursor: pointer;" for="{{ $itemm->id }}">{{ $itemm->name }}</label>
                    @endif

                @endforeach

                      @if ($errors->has('academies'))
                        <span class="error text-danger"
                              id="academies-error"
                              for="input-academies">{{ $errors->first('academies') }}</span>

                      @endif
                    </div>
        </div>

          {{-- Footer Submit Save Button --}}
          <div class=" ml-auto mr-auto mt-0 editbtn">
            <button type="submit" class="btn btn-primary m-2 mt-0 edit">{{ __('EDIT') }}</button>
        {{-- <a href="{{ route('projects.index') }}" class="btn m-2 edit">{{ __('EDIT') }}</a> --}}
        </div>
    </div>



</div>

</div>
    </form>
</x-app-layout>
<script>
    $(function(){

        $('.skill').each(function(){
            $(this).on('click', () => {
                if($(this).hasClass('btn-default2')){
                    console.log("Hello")
                    $(this).addClass('btn-selected2')
                    $(this).removeClass('btn-default2')
                }else{
                    $(this).removeClass('btn-selected2')
                    $(this).addClass('btn-default2')
                }
            })
        })
    })



    $(function() {
        $('.prof-academy-select').on('click', function(e) {
            $.each($('.prof-academy-select'), function(e) {
                $(this).removeClass('btn-selected')
                $(this).addClass('btn-default');
            });

            $(this).removeClass('btn-default')
            $(this).addClass('btn-selected')
        });
    })





</script>

resources/views/pages/profiles/index.blade.php
<x-app-layout>

    <div class="row mt-5">
        <div class="col-lg-2 offset-lg-2">
            <div class="row justify-content-center">
                <div class="col-6 mb-4">

                </div>
            </div>
        </div>
        <div class="col-lg-6">

        </div>
    </div>



</x-app-layout>

resources/views/pages/profiles/show.blade.php
<x-app-layout>
<div class="container-fluid myprofile">

    <div class="profile-left prof-row">
        <div class="profile-details d-flex mt-3">
            <div class="detail-left half mt-5">
        <div class="pic mt-5">
            @if ($user->avatar)
                <img class="img-thumbnail" name="avatar" width="90px" src="{{ url('assets/profile/'.$user->avatar) }}" alt="User image">
            @else
                <img class="img-thumbnail" width="90px"
                    src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="User image">
            @endif

            </div>
        </div>
        <div class="detail-right half mt-5">
            <div class="h4 graytitle">Name</div>
            <div class="h3 boldtitle">{{ $user->name ." " . $user->surname}}</div>
            <div class="h4 graytitle">Contact</div>
            <div class="h5 boldtitle">{{ $user->email}}</div>
        </div>
    </div>


    </div>
    <div class="profile-right prof-row mt-5">
        <div><span class="h4 graytitle">Biography</span>
        <p class="showmore mt-4 graybio">{{ $user->biography}}</p></div>

        <div class="prof-title mt-5">
        <h1 class="h3">Skills</h1>
            <div class="prof-skills">
                <div class="input-group-text skillsshow">

                          @foreach ($user->skills as $skill)

                            <input type="checkbox" name="skills[]" value="{{ $skill->id }}" id="{{ $skill->id }}" aria-label="Checkbox for following text input" class="d-none">

                            <label class="btn-default skill" style="cursor: pointer;" for="{{ $skill->id }}">{{ $skill->name }}</label>


                            @endforeach
                        </div>

            </div>
        </div>
    </div>

</div>


</x-app-layout>
<script>
document.querySelectorAll('.showmore').forEach(element => {

    if (element.outerText.length > 500) {
        let span = document.createElement('span')
        span.className = 'show t-orange'
        span.innerText = 'show more'
        element.parentNode.appendChild(span)

        let tempText = String(element.outerText)
        element.innerText = String(element.innerText).slice(0, 500)
        $(span).on('click', () => {
            element.innerText = tempText
            $(span).remove()
        })
    }
});
</script>