routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ApplicantController;
use App\Http\Controllers\ApplicationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard',                            [HomeController::class, 'index'])->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('/applications',                    ApplicationController::class)->middleware('auth');
Route::resource('/applicants',                      ApplicantController::class)->except('index')->middleware('auth');
Route::resource('/projects',                        ProjectController::class)->middleware('auth');
Route::resource('/profiles',                         ProfileController::class)->middleware('auth');

Route::get('projects/{project}/applicants/',        [ApplicantController::class, 'index'])->name('applicants.index')->middleware('auth');
Route::get('projects/{project}/applicants/{user}',  [ApplicantController::class, 'acceptApplicant'])->name('applicants.accept');
Route::get('projects/{project}/assembleTeam',       [ApplicantController::class, 'assembleTeam'])->name('applicants.assemble');
Route::get('/ajax/projects', [ProjectController::class, 'getProjects'])->name('ajax.projects');
require __DIR__.'/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function applicants()
    {
        return $this->belongsToMany(User::class, 'applicants')->withPivot('message', 'status');
    }

    public function requirements()
    {
        return $this->belongsToMany(Academy::class, 'project_requirements', 'project_id', 'academy_id');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Academy;
use App\Models\Project;
use Illuminate\Http\Request;
use App\Models\ProjectRequirement;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\ProjectsRequest;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::with('user', 'user.academy', 'applicants')
            ->where('user_id', auth()->user()->id)
            ->latest()
            ->get();

        return view('pages.projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $academies = Academy::all('id', 'name');
        return view('pages.projects.create', compact('academies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectsRequest $request)
    {

        $project = new Project();
        $project->name = $request->name;
        $project->description = $request->description;
        $project->user_id = Auth::id();
        $project->save();

        // List all arrays input
        $input['academies'] = $request->input('academies');

        $selectProjectId = Project::orderBy('id', 'desc')->first('id');
        $id = $selectProjectId->id;

        // Create academies
        foreach ($input['academies'] as $academy) {
            ProjectRequirement::create([
                'project_id' => $id,
                'academy_id' => $academy
            ]);
        }

        return redirect()->route('projects.index')->with('status', 'Project Created');

        return $request;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        return view('pages.projects.edit', ['model' => Project::where('id', $id)->first(), 'academies' => Academy::all(), 'requirements' => ProjectRequirement::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectsRequest $request, $id)
    {
        $project = Project::find($id);
        $project->name = $request->name;
        $project->description = $request->description;
        $project->user_id = Auth::id();

        // List all arrays input
        $input['academies'] = $request->input('academies');


        $project->requirements()->sync($input['academies']);


        $project->update();

        return redirect()->route('projects.index')->with('status', 'Project Created');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::find($id);


        $project->applicants()->detach();
        $project->requirements()->detach();

        $project->delete();

        return redirect()->route('projects.index')
            ->withSuccess(__('Post delete successfully.'));
    }

    public function getProjects(Request $request)
    {
        $projects = Project::with('user', 'user.academy', 'applicants')
            ->where('user_id', '!=', auth()->user()->id)
            ->when($request->has('academy_id'), function ($query) use ($request) {
                $query->whereHas('requirements', function ($query) use ($request) {
                    $query->where('academy_id', $request->academy_id);
                });
            })
            ->latest()
            ->paginate(3)
            ->withQueryString();

        return view('inc.projects', compact('projects'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/projects/create.blade.php
<x-app-layout>
    <div class="container-fluid flex flex-row create">
    <div class="row mt-5">

<form action="{{ route('projects.store') }}" method="POST">
            @csrf
        <div class="col-lg-9 left">
            <div class="row">
                <div class="pull-left">
                    <h2 class="createtitle">New Project</h2>
                </div>
                <div class="mt-4 input left form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                    <input type="text" name="name"  class="block mt-1 w-full text-line form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" required="true"  placeholder="Name of Project">
                    @if ($errors->has('name'))
                      <span class="error text-danger" 
                            id="name-error" 
                            for="input-name">{{ $errors->first('name') }}</span>

                    @endif
                </div>
                <div class="mt-4 mb-4 flex-column form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                    <strong class="createdesc">Description of project</strong><br>
                    <textarea class="form-control {{ $errors->has('description') ? ' is-invalid' : '' }} createtextarea" rows="10" cols="65" name="description" placeholder="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."></textarea>

                    @if ($errors->has('description'))
                      <span class="error text-danger" 
                            id="description-error" 
                            for="input-description">{{ $errors->first('description') }}</span>

                    @endif
                </div>
            </div>
        </div>
    </div>
       
        <div class="col-lg-5 academies right">
            <div class="row mt-5">
            <h1 class="createtitle">What I need</h1>    
            
                <div class="form-group{{ $errors->has('academies') ? ' has-danger' : '' }}">
                    <div class="input-group-text academiescheck ">
                  @foreach ($academies as $item)
                    <input type="checkbox" name="academies[]" value="{{ $item->id }}" id="sizeschck{{ $item->id }}" aria-label="Checkbox for following text input">
                      
                    <label class="btn-default" style="cursor: pointer;" for="sizeschck{{ $item->id }}">{{ $item->name }}</label>
                    
                  @endforeach
                </div>

                  @if ($errors->has('academies'))
                    <span class="error text-danger" 
                          id="academies-error" 
                          for="input-academies">{{ $errors->first('academies') }}</span>

                  @endif
                </div>

                <p class="yellowp">Please select no more than 4 options</p>

                 {{-- Footer Submit Save Button --}}
                <div class=" ml-auto mr-auto editbtn">
                    <button type="submit" class="btn btn-primary m-2 edit">{{ __('EDIT') }}</button>
                {{-- <a href="{{ route('projects.index') }}" class="btn m-2 edit">{{ __('EDIT') }}</a> --}}
                </div>
        </div>
        </div>
    
</form>
</div>
    </div>




</x-app-layout>

<script>
    $(function(){
        
        $('.academiescheck label').each(function(){
            $(this).on('click', () => {
                if($(this).hasClass('btn-default')){
                    console.log("Hello")
                    $(this).addClass('btn-selected')
                    $(this).removeClass('btn-default')
                }else{
                    $(this).removeClass('btn-selected')
                    $(this).addClass('btn-default')
                }
            })
        })
    })
</script>

resources/views/pages/projects/edit.blade.php
<x-app-layout>
    <div class="container-fluid flex flex-row create">
        <div class="row mt-5">

<form action="{{ route('projects.update', ['project' => $model->id]) }}" method="POST" autocomplete="off">
            @csrf
            @method('put')

        <div class="col-lg-9 left">
            <div class="row">
                <div class="pull-left">
                    <h2 class="createtitle">Edit Project</h2>
                </div>

                {{-- Name --}}
                <div class="mt-4 input left form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                    <input type="text" name="name"  class="block mt-1 w-full text-line form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" required="true" value="{{ $model->name }}"   placeholder="Name of Project">
                    @if ($errors->has('name'))
                      <span class="error text-danger"
                            id="name-error"
                            for="input-name">{{ $errors->first('name') }}</span>

                    @endif
                </div>

                {{-- Description edit --}}
                <div class="mt-4 mb-4 flex-column form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                    <strong class="createdesc">Description of project</strong><br>
                    <textarea class="form-control {{ $errors->has('description') ? ' is-invalid' : '' }} createtextarea" rows="10" cols="65" name="description" placeholder="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.">{{ $model->description }}</textarea>

                    @if ($errors->has('description'))
                      <span class="error text-danger"
                            id="description-error"
                            value="{{ $model->description }}"
                            for="input-description">{{ $errors->first('description') }}</span>

                    @endif
                </div>
            </div>
        </div>
    </div>

        <div class="col-lg-5 academies right">
            <div class="row mt-5">
            <h1 class="createtitle">What I need</h1>
            <div class="form-group{{ $errors->has('academies') ? ' has-danger' : '' }}">
            <div class="input-group-text academiescheck ">
            @foreach ($academies as $item)

                @php($is = true)
                  @foreach ($model->requirements as $academy)
                  {{-- {{ dd($academy->pivot->academy_id)}} --}}
                  @if ($academy->pivot->academy_id == $item->id)

                    <input type="checkbox" name="academies[]" value="{{ $item->id }}" id="sizeschck{{ $item->id }}" aria-label="Checkbox for following text input" checked>

                    <label class="btn-selected" style="cursor: pointer;" for="sizeschck{{ $item->id }}">{{ $item->name }}</label>

                      @php($is = false)
                      @break
                  @endif
                  @endforeach



                @if($is)
                <input type="checkbox" name="academies[]" value="{{ $item->id }}" id="sizeschck{{ $item->id }}" aria-label="Checkbox for following text input">
                <label class="btn-default" style="cursor: pointer;" for="sizeschck{{ $item->id }}">{{ $item->name }}</label>
                @endif

            @endforeach

                  @if ($errors->has('academies'))
                    <span class="error text-danger"
                          id="academies-error"
                          for="input-academies">{{ $errors->first('academies') }}</span>

                  @endif
                </div>
            </div>
                <p class="yellowp">Please select no more than 4 options</p>

                 {{-- Footer Submit Save Button --}}
                <div class=" ml-auto mr-auto editbtn">
                    <button type="submit" class="btn btn-primary m-2 edit">{{ __('EDIT') }}</button>
                </div>




        </div>
        </div>
</form>
    </div>



</x-app-layout>

<script>
    $(function(){

        $('.academiescheck label').each(function(){
            $(this).on('click', () => {
                if($(this).hasClass('btn-default')){
                    console.log("Hello")
                    $(this).addClass('btn-selected')
                    $(this).removeClass('btn-default')
                }else{
                    $(this).removeClass('btn-selected')
                    $(this).addClass('btn-default')
                }
            })
        })
    })
</script>

resources/views/pages/projects/index.blade.php
<x-app-layout>
    <div class="col-6 mb-4 projecttitle">
        <h2>Have a new idea to make the world better?</h2>
        <span class="d-flex">Create new project<a href="{{ route('projects.create') }}"><img src="../icons/1.png" alt="Plus" class="w-25">
        </a ></span>
    </div>
    <div class="row justify-content-center">

    <div class="row mt-5">

        </div>
        <div class="col-lg-8">
            @foreach ($projects as $project)
                @include('inc.project-card')
            @endforeach
        </div>
    </div>



</x-app-layout>

<script>
    $('.show-more').on('click', function(){
        $('.showmorediv').css("max-height" , "initial");
        });

    </script>

resources/views/pages/projects/store.blade.php
<x-app-layout>

    <div class="row mt-5">
        <div class="col-lg-2 offset-lg-2">
            <div class="row justify-content-center">

            </div>
        </div>
        <div class="col-lg-6">

        </div>
    </div>


    
</x-app-layout>